FROM jenkins/jnlp-slave:alpine as jnlp

FROM maven:3-jdk-11-slim

RUN apt-get update && \
    apt-get install -y \
        git

COPY --from=jnlp /usr/local/bin/jenkins-slave /usr/local/bin/jenkins-agent
COPY --from=jnlp /usr/share/jenkins/slave.jar /usr/share/jenkins/slave.jar

ENTRYPOINT ["/usr/local/bin/jenkins-agent"]
