FROM jenkins4eval/jnlp-agent:latest-windows as jnlp

FROM maven:3-jdk-8-windows

COPY --from=jnlp C:/ProgramData/Jenkins/jenkins-agent.ps1 C:/ProgramData/Jenkins/jenkins-agent.ps1
COPY --from=jnlp C:/ProgramData/Jenkins/agent.jar C:/ProgramData/Jenkins/agent.jar

ENV JAVA_HOME ${JAVA_HOME}

ENTRYPOINT ["powershell.exe", "-f", "C:/ProgramData/Jenkins/jenkins-agent.ps1"]
