FROM jenkins/inbound-agent:alpine as jnlp

FROM maven:3.6.3-jdk-8-slim

RUN apt-get update && \
    apt-get install -y \
        git \
        libfontconfig1 \
        libfreetype6

ARG adduser='useradd -m'

