# escape=`
ARG JAVA_VERSION=19.0.1_10
FROM eclipse-temurin:${JAVA_VERSION}-jdk-windowsservercore-1809 AS core
# Use inbound-agent's JDK11 only for running jenkins agent, not as default java
FROM jenkins/inbound-agent:3077.vd69cf116da_6f-3-jdk11-nanoserver-1809

# ProgressPreference => Disable Progress bar for faster downloads
SHELL ["pwsh.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Retrieve JDK11 for running jenkins agent process but do not use it as default
# Use ENV and not ARG : https://docs.docker.com/engine/reference/builder/#using-arg-variables
ENV JAVA_HOME=C:/tools/jdk-19
COPY --from=core C:/openjdk-19 "${JAVA_HOME}"

# https://github.com/StefanScherer/dockerfiles-windows/tree/master/golang-issue-21867
COPY --from=core C:/windows/system32/netapi32.dll C:/windows/system32/netapi32.dll

ARG MAVEN_VERSION=3.8.6
RUN Invoke-WebRequest -Uri "https://archive.apache.org/dist/maven/maven-3/${env:MAVEN_VERSION}/binaries/apache-maven-${env:MAVEN_VERSION}-bin.zip" -OutFile ${env:TEMP}/apache-maven.zip ; `
  Expand-Archive -Path "${env:TEMP}/apache-maven.zip -Destination" C:\tools ; `
  Remove-Item ${env:TEMP}/apache-maven.zip ;

ENV MAVEN_HOME "C:\tools\apache-maven-${MAVEN_VERSION}"
ENV PATH="${JAVA_HOME}\bin;${PATH};${MAVEN_HOME}\bin"
