# escape=`
# this JAVA version is the one used for the execution of the agent process and must match the controller version
ARG JAVA_VERSION=11.0.17_8
FROM eclipse-temurin:${JAVA_VERSION}-jdk-windowsservercore-1809 AS core
FROM jenkins/inbound-agent:jdk17-nanoserver-1809

# ProgressPreference => Disable Progress bar for faster downloads
SHELL ["pwsh.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Retrieve JDK11 for running jenkins agent process but do not use it as default
COPY --from=core C:/openjdk-11 C:/tools/jdk-11

# https://github.com/StefanScherer/dockerfiles-windows/tree/master/golang-issue-21867
COPY --from=core C:/windows/system32/netapi32.dll C:/windows/system32/netapi32.dll

ARG MAVEN_VERSION=3.8.6
RUN Invoke-WebRequest -Uri "https://archive.apache.org/dist/maven/maven-3/${env:MAVEN_VERSION}/binaries/apache-maven-${env:MAVEN_VERSION}-bin.zip" -OutFile ${env:TEMP}/apache-maven.zip ; `
  Expand-Archive -Path "${env:TEMP}/apache-maven.zip -Destination" C:\tools ; `
  Remove-Item ${env:TEMP}/apache-maven.zip ;

ENV MAVEN_HOME "C:\tools\apache-maven-${MAVEN_VERSION}"
ENV PATH="${PATH};${MAVEN_HOME}\bin"
